Repository MYONGSIK/Server, pull requests merged in 2023-04, with the labels that each got.

#105 [feature/store-service] 가게 테이블에 위도와 경도 컬럼 추가에 따른 코드 수정
  .github/workflows/CI_Dev.yml
  src/main/java/com/example/myongsick/domain/scrap/dto/CountResponse.java
  src/main/java/com/example/myongsick/domain/scrap/dto/ScrapCountResponse.java
  src/main/java/com/example/myongsick/domain/scrap/dto/ScrapRequest.java
  src/main/java/com/example/myongsick/domain/scrap/dto/ScrapResponse.java
  src/main/java/com/example/myongsick/domain/scrap/entity/Store.java
  src/main/java/com/example/myongsick/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapServiceImpl.java
Labels: implement

#109 가게 생성 시, 위도 경도 데이터 누락 이슈 해결
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapServiceImpl.java
Labels: hotfix

#112 [feature/store-service] 가게 상세 조회 API
  src/main/java/com/example/myongsick/domain/scrap/controller/ScarpController.java
  src/main/java/com/example/myongsick/domain/scrap/exception/NotFoundStoreException.java
  src/main/java/com/example/myongsick/domain/scrap/exception/ScrapExceptionEnum.java
  src/main/java/com/example/myongsick/domain/scrap/repository/StoreRepository.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapService.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapServiceImpl.java
Labels: implement

#115 [refactor/store-service] review, scrap, user 패키지 내 코드 정리
  src/main/java/com/example/myongsick/domain/review/dto/ReviewRequest.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/example/myongsick/domain/scrap/dto/ScrapCountResponse.java
  src/main/java/com/example/myongsick/domain/scrap/entity/Scrap.java
  src/main/java/com/example/myongsick/domain/scrap/entity/Store.java
  src/main/java/com/example/myongsick/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/example/myongsick/domain/scrap/repository/StoreRepository.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapServiceImpl.java
  src/main/java/com/example/myongsick/domain/user/dto/UserRequest.java
  src/main/java/com/example/myongsick/domain/user/dto/UserResponse.java
  src/main/java/com/example/myongsick/domain/user/service/UserServiceImpl.java
Labels: refactor

#119 [Feature/querydsl] QueryDSL 적용 완료하였습니다.
  .idea/compiler.xml
  build.gradle
Labels: implement

#120 [feature/scrap-service] native query를 querydsl로 변경
  src/main/java/com/example/myongsick/domain/scrap/dto/ScrapCountResponse.java
  src/main/java/com/example/myongsick/domain/scrap/repository/ScrapRepositoryCustom.java
  src/main/java/com/example/myongsick/domain/scrap/repository/ScrapRepositoryImpl.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapService.java
  src/main/java/com/example/myongsick/domain/scrap/service/ScrapServiceImpl.java
  src/main/java/com/example/myongsick/global/config/QueryDslConfig.java
Labels: refactor, implement
