Repository MYONGSIK/Server, pull requests merged in 2023-02, with the labels that each got.

#35 [infra/ci test] Github Actions 테스트를 위한 application.yml 파일 수정
  src/main/resources/application.yml
Labels: infra

#38 #34 CI 테스트를 위한 실패 테스트 케이스 코드 작성
  src/test/java/com/example/myongsick/domain/food/service/FoodServiceImplTest.java
Labels: infra

#45 [refactor/db-change] 엔티티 재정의
  build.gradle
  src/main/java/com/example/myongsick/domain/food/controller/FoodController.java
  src/main/java/com/example/myongsick/domain/v2/Area.java
  src/main/java/com/example/myongsick/domain/v2/Meal.java
  src/main/java/com/example/myongsick/domain/v2/MealType.java
  src/main/java/com/example/myongsick/domain/v2/Review.java
  src/main/java/com/example/myongsick/domain/v2/Scrap.java
  src/main/java/com/example/myongsick/domain/v2/StatusType.java
  src/main/java/com/example/myongsick/domain/v2/User.java
  src/main/java/com/example/myongsick/domain/v2/Week.java
Labels: refactor

#48 [feature/review-service] 리뷰 작성 및 조회 API 기능 개발
  build.gradle
  src/main/java/com/example/myongsick/domain/meal/Meal.java
  src/main/java/com/example/myongsick/domain/meal/MealRepository.java
  src/main/java/com/example/myongsick/domain/review/controller/ReviewController.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewRequest.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewResponse.java
  src/main/java/com/example/myongsick/domain/review/entity/Review.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewException.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewExceptionEnum.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/example/myongsick/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewService.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/example/myongsick/domain/user/User.java
  src/main/java/com/example/myongsick/domain/user/UserRepository.java
  src/main/java/com/example/myongsick/domain/v2/Area.java
  src/main/java/com/example/myongsick/domain/v2/Meal.java
  src/main/java/com/example/myongsick/domain/v2/Review.java
  src/main/java/com/example/myongsick/domain/v2/Scrap.java
  src/main/java/com/example/myongsick/domain/v2/User.java
  src/main/java/com/example/myongsick/domain/v2/WeekMeal.java
  src/test/java/com/example/myongsick/domain/food/service/FoodServiceImplTest.java
  src/test/java/com/example/myongsick/domain/review/service/ReviewServiceImplTest.java
Labels: implement

#50 #47 음식 일, 주 단위 조회 추가, 지역 추가, 식단 추가, 식단 한번에 추가 기능 구현 완료
  Dockerfile
  build.gradle
  src/main/java/com/example/myongsick/domain/Meal/controller/MealController.java
  src/main/java/com/example/myongsick/domain/Meal/dto/request/MealCreateReq.java
  src/main/java/com/example/myongsick/domain/Meal/dto/request/MealNotRegisterReq.java
  src/main/java/com/example/myongsick/domain/Meal/dto/response/MealResponse.java
  src/main/java/com/example/myongsick/domain/Meal/entity/Area.java
  src/main/java/com/example/myongsick/domain/Meal/entity/Meal.java
  src/main/java/com/example/myongsick/domain/Meal/entity/MealType.java
  src/main/java/com/example/myongsick/domain/Meal/entity/StatusType.java
  src/main/java/com/example/myongsick/domain/Meal/exception/MealException.java
  src/main/java/com/example/myongsick/domain/Meal/exception/MealExceptionEnum.java
  src/main/java/com/example/myongsick/domain/Meal/exception/excute/AlreadyAreaException.java
  src/main/java/com/example/myongsick/domain/Meal/exception/excute/NotFoundAreaException.java
  src/main/java/com/example/myongsick/domain/Meal/exception/excute/NotFoundWeekException.java
  src/main/java/com/example/myongsick/domain/Meal/exception/excute/NotOperatedException.java
  src/main/java/com/example/myongsick/domain/Meal/repository/AreaRepository.java
  src/main/java/com/example/myongsick/domain/Meal/repository/MealRepository.java
  src/main/java/com/example/myongsick/domain/Meal/service/MealService.java
  src/main/java/com/example/myongsick/domain/Meal/service/MealServiceImpl.java
  src/main/java/com/example/myongsick/domain/food/controller/FoodController.java
  src/main/java/com/example/myongsick/domain/food/dto/request/DinnerAddRequest.java
  src/main/java/com/example/myongsick/domain/food/entity/Week.java
  src/main/java/com/example/myongsick/domain/food/exception/NotOperated.java
  src/main/java/com/example/myongsick/domain/food/service/FoodServiceImpl.java
  src/main/java/com/example/myongsick/domain/review/controller/ReviewController.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewRequest.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewResponse.java
  src/main/java/com/example/myongsick/domain/review/entity/Review.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewException.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewExceptionEnum.java
  src/main/java/com/example/myongsick/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/example/myongsick/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewService.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/example/myongsick/domain/user/User.java
  src/main/java/com/example/myongsick/domain/user/UserRepository.java
  src/main/java/com/example/myongsick/domain/v2/Scrap.java
  src/main/java/com/example/myongsick/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/myongsick/global/object/ApplicationErrorResponse.java
  src/main/resources/application.yml
  src/test/java/com/example/myongsick/domain/food/service/FoodServiceImplTest.java
  src/test/java/com/example/myongsick/domain/review/service/ReviewServiceImplTest.java
Labels: implement

#52 [hotfix/food service] Food Controller URL 수정
  src/main/java/com/example/myongsick/domain/food/controller/FoodController.java
Labels: hotfix

#54 #47 패키지 이름 변경에 따른 참조 구조 재설정
  src/main/java/com/example/myongsick/domain/meal/controller/MealController.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealCreateReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealNotRegisterReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/response/MealResponse.java
  src/main/java/com/example/myongsick/domain/meal/entity/Area.java
  src/main/java/com/example/myongsick/domain/meal/entity/Meal.java
  src/main/java/com/example/myongsick/domain/meal/entity/MealType.java
  src/main/java/com/example/myongsick/domain/meal/entity/StatusType.java
  src/main/java/com/example/myongsick/domain/meal/exception/MealException.java
  src/main/java/com/example/myongsick/domain/meal/exception/MealExceptionEnum.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/AlreadyAreaException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotFoundAreaException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotFoundWeekException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotOperatedException.java
  src/main/java/com/example/myongsick/domain/meal/repository/AreaRepository.java
  src/main/java/com/example/myongsick/domain/meal/repository/MealRepository.java
  src/main/java/com/example/myongsick/domain/meal/service/MealService.java
  src/main/java/com/example/myongsick/domain/meal/service/MealServiceImpl.java
Labels: implement

#56 #55 식단 좋아요/싫어요 평가 기능 구현 완료
  README.md
  src/main/java/com/example/myongsick/domain/meal/controller/MealController.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealCreateReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealEvaluateReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealNotRegisterReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/response/MealResponse.java
  src/main/java/com/example/myongsick/domain/meal/entity/Area.java
  src/main/java/com/example/myongsick/domain/meal/entity/Meal.java
  src/main/java/com/example/myongsick/domain/meal/entity/MealEvaluate.java
  src/main/java/com/example/myongsick/domain/meal/entity/MealType.java
  src/main/java/com/example/myongsick/domain/meal/entity/StatusType.java
  src/main/java/com/example/myongsick/domain/meal/exception/MealException.java
  src/main/java/com/example/myongsick/domain/meal/exception/MealExceptionEnum.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/AlreadyAreaException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotFoundAreaException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotFoundWeekException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotOperatedException.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotfoundMealException.java
  src/main/java/com/example/myongsick/domain/meal/repository/AreaRepository.java
  src/main/java/com/example/myongsick/domain/meal/repository/MealRepository.java
  src/main/java/com/example/myongsick/domain/meal/service/MealService.java
  src/main/java/com/example/myongsick/domain/meal/service/MealServiceImpl.java
Labels: implement

#57 main <- develop
  src/main/java/com/example/myongsick/domain/meal/controller/MealController.java
  src/main/java/com/example/myongsick/domain/meal/dto/request/MealEvaluateReq.java
  src/main/java/com/example/myongsick/domain/meal/dto/response/MealResponse.java
  src/main/java/com/example/myongsick/domain/meal/entity/Meal.java
  src/main/java/com/example/myongsick/domain/meal/entity/MealEvaluate.java
  src/main/java/com/example/myongsick/domain/meal/exception/MealExceptionEnum.java
  src/main/java/com/example/myongsick/domain/meal/exception/excute/NotfoundMealException.java
  src/main/java/com/example/myongsick/domain/meal/service/MealService.java
  src/main/java/com/example/myongsick/domain/meal/service/MealServiceImpl.java
Labels: implement

#58 [feature/review-service] Swagger에 노출되는 api 설명 추가
  src/main/java/com/example/myongsick/domain/review/controller/ReviewController.java
Labels: refactor

#62 [feature/review-service] 리뷰 등록 시, 식사가 아닌 날짜를 기준으로 변경
  src/main/java/com/example/myongsick/domain/review/controller/ReviewController.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewRequest.java
  src/main/java/com/example/myongsick/domain/review/dto/ReviewResponse.java
  src/main/java/com/example/myongsick/domain/review/entity/Review.java
  src/main/java/com/example/myongsick/domain/review/service/ReviewServiceImpl.java
  src/test/java/com/example/myongsick/domain/review/service/ReviewServiceImplTest.java
Labels: bug

#68 #47 주간 식단 조회 기능 구현
  src/main/java/com/example/myongsick/domain/meal/controller/MealController.java
  src/main/java/com/example/myongsick/domain/meal/dto/response/MealResponse.java
  src/main/java/com/example/myongsick/domain/meal/repository/MealRepository.java
  src/main/java/com/example/myongsick/domain/meal/service/MealService.java
  src/main/java/com/example/myongsick/domain/meal/service/MealServiceImpl.java
Labels: implement

#76 #46 유저 중복 등록인 경우, 오류 코드 변경
  src/main/java/com/example/myongsick/domain/user/exception/UserExceptionEnum.java
Labels: hotfix
